### ISSUE TITLE
Rake task calls Kernel.exit

### ISSUE THREAD

**Issue by tabolario** [causes/scss-lint#338]
As of bd0ffa9137c2f30f2840766816995a164f628b7a, The Rake task calls `Kernel.exit` after the CLI is finished completing. Is there a particular reason this is done? It prevents the Rake task from being chained with others, as it keeps any subsequent tasks from being invoked.

As for my own use case here, I run the scss-lint task that I've defined as part of my `lint` namespace in a project, which is also run in the default task like `default: %i(lint spec)`, and this prevents the spec task from ever being run.

**Comment by tabolario** [comment]
As a suggestion, would it make more sense to have the Rake task raise an exception if the result from `SCSSLint::CLI.new.run` is not `CLI::EXIT_CODES[:ok]`, and just print a message and allow the task to return execution if there were no errors?

**Comment by tabolario** [comment]
Sorry, I take back what I said about the exception. Calling `Kernel.exit` in the case of an error code from the CLI run is the way to do it, so my main issue is just back to `Kernel.exit` being called for a successful run :smile:

**Comment by sds** [comment]
Hey @tabolario,

This functionality was actually introduced by #334, in which I specifically mentioned this would be a problem when using the rake task as a dependency.

Now that I have someone actually complaining, I'm happy to only call `Kernel.exit` in the event of a failure.

Fixed in f8b44ed68eccb96e5508105d2afd848f91513335. Thanks!
