### ISSUE TITLE
UrlFormat for CDN and external resources

### ISSUE THREAD

**Issue by FranciscoP** [causes/scss-lint#401]
While I agree to leave out the protocol (`//www.example.com/...`), sometimes it's desirable to include an external asset, as when using a CDN. However scss-lint warns about `UrlFormat`. Basically, it's implying not to use CDN or external resources.

Possible fix: add a parameter to define the base domain and only display a warning for the ones from that domain:

Configuration Option | Description
-----------------------------|---------------------------------------------------------
`base_domain`          | The domain that should be shortened. Other domains (as CDNs) are allowed.

**Comment by sds** [comment]
It seems like a smell to hard-code a CDN domain in your Sass documents. What happens if your CDN were to change? Having to update all the references would be painful.

Why not define a helper function `cdn-url` so you can change the CDN domain in one place?

In other words, I'm suggesting that this linter is pushing you in the right direction and that there is no need to add exceptions for certain domains.

**Comment by sds** [comment]
Closing due to lack of response.

**Comment by FranciscoP** [comment]
I thought they were rethorical questions. I agree with your conclusion and the closing of the issue.

**Comment by sds** [comment]
Sorry, didn't mean for the questions to sound rhetorical. I was genuinely interested in understanding the potential use case here.

Thanks wanting to suggest ways to improve `scss-lint`!
